import './styles/main.css'
import { createApp } from 'vue'
import { createRouter, createWebHistory } from 'vue-router'
// import routes generated by Voie
import routes from 'voie-pages'

import App from './App.vue'
import { i18n } from './locales'

const app = createApp(App)

const router = createRouter({
    history: createWebHistory(),
    routes,
})

app.use(i18n)
app.use(router)

app.mount('#app')
